package com.sisnet.constantes;
public final class ConstantesHTML {
  public static final String const_AtributoID = " id=\"";
  public static final String const_AtributoNAME = " name=\"";
  public static final String const_AtributoACTION = " action=\"";
  public static final String const_AtributoMETHOD = " method=\"";
  public static final String const_AtributoENCTYPE = " enctype=\"";
  public static final String const_AtributoTYPE = " type=\"";
  public static final String const_AtributoCLASS = " class=\"";
  public static final String const_AtributoVALUE = " value=\"";
  public static final String const_AtributoMAXLENGTH = " maxlength=\"";
  public static final String const_AtributoSRC = " src=\"";
  public static final String const_AtributoHREF = " href=\"";
  public static final String const_AtributoPXROWS = " px rows=\"";
  public static final String const_AtributoALIGN = " align=\"";
  public static final String const_AtributoWIDTH = " width=\"";
  public static final String const_AtributoCOLSPAN = " colspan=\"";
  public static final String const_AtributoROWSPAN = " rowspan=\"";
  public static final String const_AtributoONSUBMIT = " onSubmit=\"";
  public static final String const_AtributoONKEYPRESS = " onKeyPress=\"";
  public static final String const_AtributoONBLUR = " onBlur=\"";
  public static final String const_AtributoONCLICK = " onClick=\"";
  public static final String const_AtributoREADONLY = " readonly ";
  public static final String const_AtributoDISABLED = " disabled ";
  public static final String const_AtributoCHECKED = " checked ";
  public static final String const_AtributoSELECTED = " selected ";
  public static final String const_CerrarEtiquetaConSaltoLinea = ">\n";
  public static final String const_CerrarEtiqueta = "> ";
  public static final String const_CerrarAtributo = "\"";
  public static final String const_EtiquetaFORM = " <form ";
  public static final String const_EtiquetaCerrarFORM = " </form>\n";
  public static final String const_EtiquetaINPUT = " <input ";
  public static final String const_EtiquetaIMG = " <img ";
  public static final String const_EtiquetaA = " <a ";
  public static final String const_EtiquetaCerrarA = " </a>\n";
  public static final String const_EtiquetaOPTION = " <option ";
  public static final String const_EtiquetaCerrarOPTION = " </option>\n";
  public static final String const_EtiquetaSELECT = " <select ";
  public static final String const_EtiquetaCerrarSELECT = " </select>\n";
  public static final String const_EtiquetaTEXTAREA = " <textarea ";
  public static final String const_EtiquetaCerrarTEXTAREA = " </textarea>\n ";
  public static final String const_EtiquetaTH = " <th ";
  public static final String const_EtiquetaCerrarTH = " </th>\n ";
  public static final String const_EtiquetaTR = " <tr ";
  public static final String const_EtiquetaCerrarTR = " </tr>\n ";
  public static final String const_EtiquetaTABLE = " <table ";
  public static final String const_EtiquetaCerrarTABLE = " </table>\n ";
  public static final String const_EtiquetaPRE = " <pre>";
  public static final String const_EtiquetaCerrarPRE = " </pre>\n ";
  public static final String const_MetodoPOST = "post";
  public static final String const_MULTIPARTFORMDATA = "multipart/form-data";
  public static final String const_TipoTEXT = "text";
  public static final String const_TipoFILE = "file";
  public static final String const_TipoCHECKBOX = "checkbox";
  public static final String const_TipoBUTTON = "button";
  public static final String const_TipoSUBMIT = "submit";
  public static final String const_TipoHIDDEN = "hidden";
  public static final String const_TipoIMAGE = "image";
  public static final String const_TipoPASSWORD = "password";
  public static final String const_AlineacionCENTER = "center";
  public static final String const_AlineacionLEFT = "left";
  public static final String const_AlineacionRIGTH = "rigth";
  public static final String const_AlineacionJUSTIFY = "justify";
  public static final int const_AlineacionCentrada = 1;
  public static final int const_AlineacionIzquierda = 2;
  public static final int const_AlineacionDerecha = 3;
  public static final int const_AlineacionJustificada = 4;
  public static final int const_TipoControlText = 1;
  public static final int const_TipoControlFecha = 2;
  public static final int const_TipoControlTextArea = 3;
  public static final int const_TipoControlFckEditor = 4;
  public static final int const_TipoControlFile = 5;
  public static final int const_TipoControlSelect = 6;
  public static final int const_TipoControlCheckBox = 7;
}
/* Location:              D:\Personal\sisnet\sisnetMasterApp\sisnetapp.war!\WEB-INF\classes\com\sisnet\constantes\ConstantesHTML.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */