package com.sisnet.constantes;
public final class ConstantesAdministradorSQL {
  public static final String const_CadenaWITH_OWNER = " whith owner = postgres ";
  public static final String const_CadenaENCODING = " encoding = 'LATIN1'; ";
  public static final String const_CadenaTABLESPACE = " tablespace = pg_default; ";
  public static final String const_CadenaCREATE_DATABASE = "create database ";
  public static final String const_CadenaCREATE_TABLE = "create table ";
  public static final String const_CadenaCREATE_VIEW = "create view ";
  public static final String const_CadenaCREATE_UNIQUE_INDEX = " create unique index ";
  public static final String const_CadenaCREATE_ROL = " create rol ";
  public static final String const_CadenaALTER_DATABASE = "alter database ";
  public static final String const_CadenaALTER_TABLE = "alter table ";
  public static final String const_CadenaALTER_COLUMN = " alter column ";
  public static final String const_CadenaALTER = " alter ";
  public static final String const_CadenaDROP_DATABASE = "drop database ";
  public static final String const_CadenaDROP_TABLE = "drop table ";
  public static final String const_CadenaDROP_VIEW = "drop view ";
  public static final String const_CadenaDROP_COLUMN = " drop column ";
  public static final String const_CadenaDROP_INDEX = " drop index ";
  public static final String const_CadenaDROP_CONSTRAINT = " drop constraint ";
  public static final String const_CadenaDROP_ROL = " drop rol ";
  public static final String const_CadenaADD_COLUMN = " add column ";
  public static final String const_CadenaADD_CONSTRAINT = " add constraint ";
  public static final String const_CadenaCOMMIT = "commit;";
  public static final String const_CadenaROLLBACK = "rollback;";
  public static final String const_CadenaRENAME = " rename ";
  public static final String const_CadenaDELETE = " delete ";
  public static final String const_CadenaDROP = " drop ";
  public static final String const_CadenaNOT_NULL = " not null ";
  public static final String const_CadenaCASCADE = " cascade ";
  public static final String const_CadenaPRIMARY_KEY = " primary key ";
  public static final String const_CadenaFOREIGN_KEY = " foreign key ";
  public static final String const_CadenaREFERENCES = " references ";
  public static final String const_CadenaLOGIN = " login ";
  public static final String const_CadenaCREATEDB = " createdb ";
  public static final String const_CadenaTYPE = " type ";
  public static final String const_CadenaCOLUMN = " column ";
  public static final String const_CadenaDefaultNumero = " default 0 ";
  public static final String const_CadenaDefaultTexto = " default '' ";
  public static final String const_CadenaINSERT_INTO = "insert into ";
  public static final String const_CadenaUPDATE = "update ";
  public static final String const_CadenaSELECT = "select ";
  public static final String const_CadenaVALUES = " values( ";
  public static final String const_CadenaCOUNT = "count";
  public static final String const_CadenaFROM = " from ";
  public static final String const_CadenaWHERE = " where ";
  public static final String const_CadenaDISTINCT = " distinct ";
  public static final String const_CadenaORDERBY = " order by ";
  public static final String const_CadenaGROUPBY = " group by ";
  public static final String const_CadenaLOIMPORT = " lo_import( ";
  public static final String const_CadenaLOEXPORT = " lo_export( ";
  public static final String const_CadenaASC = " asc ";
  public static final String const_CadenaDESC = " desc ";
  public static final String const_CadenaSET = " set ";
  public static final String const_CadenaMAX = " max(";
  public static final String const_CadenaIN = " in ";
  public static final String const_CadenaAS = " as ";
  public static final String const_CadenaAND = " and ";
  public static final String const_CadenaOR = " or ";
  public static final String const_CadenaTO = " to ";
  public static final String const_CadenaON = " on ";
  public static final String const_CadenaNOT_IN = " not in ";
  public static final String const_CadenaISNULL = " isnull ";
  public static final String const_CadenaISNOTNULL = " is not null ";
  public static final String const_CadenaHAVING = " having ";
  public static final String const_CadenaBETWEEN = " between ";
  public static final String const_CadenaNOT_BETWEEN = " not between ";
  public static final String const_CadenaLIKE = " like ";
  public static final String const_CadenaNOTLIKE = " not like ";
  public static final String const_CadenaSUM = " sum( ";
  public static final String const_CadenaMIN = " min(";
  public static final String const_CadenaUPPER = " upper(";
  public static final String const_CadenaComodinSELECCION = "* ";
  public static final String const_CadenaComodinCOMPARACION = "%";
  public static final String const_CadenaIGUAL = " = ";
  public static final String const_CadenaDIFERENTE = " <> ";
  public static final String const_CadenaMAYORQUE = " > ";
  public static final String const_CadenaMENORQUE = " < ";
  public static final String const_CadenaMAYORIGUAL = " >= ";
  public static final String const_CadenaMENORIGUAL = " <= ";
  public static final String const_CadenaCountTotalRegistros = " count(*) as totalregistros ";
  public static final String const_TablaPostgresPGDATABASE = "pg_database ";
  public static final String const_TablaPostgresPGCONSTRAINT = "pg_constraint ";
  public static final String const_TablaPostgresPGINDEXES = "pg_indexes ";
  public static final String const_AtributoPostgresDATNAME = "datname ";
  public static final String const_AtributoPostgresCONNAME = "conname ";
  public static final String const_AtributoPostgresINDEXNAME = "indexname";
  public static final String const_CadenaTipoDatoINTEGER = "integer";
  public static final String const_CadenaTipoDatoVARCHAR = "varchar";
  public static final String const_CadenaTipoDatoNUMERIC = "numeric";
  public static final String const_CadenaTipoDatoDATE = "date";
  public static final String const_CadenaTipoDatoTIME = "time";
  public static final String const_CadenaTipoDatoBOOL = "bool";
  public static final String const_CadenaTipoDatoCONTRASENA = "contrasena";
  public static final String const_CadenaTipoDatoBYTEA = "bytea";
  public static final int const_TimeOutConsultaActualizacion = 1000;
  public static final int const_TimeOutConsultaSeleccion = 6000;
  public static final int const_NoHuboErrorConsultaActualizacion = 0;
  public static final int const_NoHuboErrorConsulta = 0;
  public static final String const_CadenaPrefijoPk = "pk";
  public static final String const_CadenaPrefijoFk = "fk";
  public static final String const_CadenaPrefijoIdx = "idx";
  public static final int const_TipoSeleccionTodasAplicaciones = 0;
  public static final int const_TipoSeleccionSoloAplicaciones = 1;
  public static final int const_TipoSeleccionSoloAplicacionesTabla = 2;
  public static final int const_TipoSeleccionSoloAplicacionesVisibles = 3;
  public static final int const_TipoSeleccionSoloAplicacionesTablaVisibles = 4;
}
/* Location:              D:\Personal\sisnet\sisnetMasterApp\sisnetapp.war!\WEB-INF\classes\com\sisnet\constantes\ConstantesAdministradorSQL.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */